version: '3'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: modern-resume-theme
    command: jekyll serve --force_polling --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./:/srv/jekyll
